name: Jekyll site CI

on: [push, pull_request]

jobs:
  build:
    if: contains(toJson(github.event.commits), '[skip jekyll]') == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}/docs:/srv/jekyll -v ${{ github.workspace }}/docs/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chown jekyll:jekyll /srv/jekyll/Gemfile.lock && \
        chown jekyll:jekyll /srv/jekyll/Gemfile && chmod 777 /srv/jekyll && jekyll build --future"
